abstract class MedicalcentersStates{}
class InitMedicalState extends MedicalcentersStates{}
class GetMedicalCentersLoadingState extends MedicalcentersStates{}
class GetMedicalCentersSuccessState extends MedicalcentersStates{}
class GetMedicalCentersErrosState extends MedicalcentersStates{}